### ISSUE TITLE
Not Really An Issue (Suggestion)

### ISSUE THREAD

**Issue by cs4233117** [ErrorGamer2000/cs4233117-s-website#1]
We should have the discussions part.

Sincerely,
cs4233117 also known as small brain (xD)

**Comment by ErrorGamer2000** [comment]
Ok, I'll see. I will probably finish it within a month...we'll see. I am most likely going to finally get [Visual Studio Code](code.visualstudio.com) pretty soon, and that is going to be a very steep learning curve.
